import datetime
import os
from collections.abc import Mapping
from typing import Literal, Self

class SeexError(RuntimeError): ...
class MetricQueueFullError(SeexError): ...
class MetricWriterFailedError(SeexError): ...
class MetricDrainTimeoutError(SeexError): ...
class MetricFlushError(SeexError): ...
class MetricFlushTimeoutError(SeexError): ...
class RunClosedError(SeexError): ...
class InvalidRunStateError(SeexError): ...
class RunAlreadyExistsError(SeexError): ...
class RunAlreadyActiveError(SeexError): ...
class InvalidConfigurationError(SeexError): ...
class StorageError(SeexError): ...
class ApiClosedError(SeexError): ...

class Settings:
    def __init__(
        self,
        *,
        catalog_backend: Literal["duckdb", "sqlite"] | None = None,
        catalog_path: str | os.PathLike[str] | None = None,
        data_path: str | os.PathLike[str] | None = None,
        metric_queue_capacity: int = 65536,
        s3_endpoint: str | None = None,
        s3_access_key_id: str | None = None,
        s3_secret_access_key: str | None = None,
        s3_session_token: str | None = None,
        s3_region: str | None = None,
        s3_path_style: bool | None = None,
        s3_use_ssl: bool | None = None,
    ) -> None: ...
    @property
    def catalog_backend(self) -> Literal["duckdb", "sqlite"] | None: ...
    @property
    def catalog_path(self) -> str | os.PathLike[str] | None: ...
    @property
    def data_path(self) -> str | os.PathLike[str] | None: ...
    @property
    def metric_queue_capacity(self) -> int: ...
    @property
    def s3_endpoint(self) -> str | None: ...
    @property
    def s3_access_key_id(self) -> str | None: ...
    @property
    def s3_secret_access_key(self) -> str | None: ...
    @property
    def s3_session_token(self) -> str | None: ...
    @property
    def s3_region(self) -> str | None: ...
    @property
    def s3_path_style(self) -> bool | None: ...
    @property
    def s3_use_ssl(self) -> bool | None: ...

class Run:
    @property
    def run_id(self) -> str: ...
    @property
    def project_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def status(self) -> Literal["running", "finished", "failed"]: ...
    def log(
        self,
        data: Mapping[str, int | float],
        *,
        step: int | None = None,
        commit: bool | None = None,
    ) -> None: ...
    def finish(self, exit_code: int | None = None) -> None: ...
    def diagnostics(self) -> Diagnostics: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...

class MetricSeries:
    @property
    def axis(self) -> Literal["step", "relative_time", "timestamp"]: ...
    @property
    def points(self) -> list[MetricPoint]: ...
    @property
    def source_count(self) -> int: ...
    @property
    def downsampled(self) -> bool: ...
    @property
    def completeness(self) -> Literal["complete", "partial", "unavailable", "invalid"]: ...
    @property
    def reasons(self) -> list[str]: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class RunRecord:
    @property
    def run_id(self) -> str: ...
    @property
    def project_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def status(self) -> Literal["running", "finished", "failed"]: ...
    @property
    def created_at(self) -> str: ...
    @property
    def started_at(self) -> str: ...
    @property
    def finished_at(self) -> str | None: ...
    def metrics(self) -> list[MetricSummary]: ...
    def metric_summary(self, metric_key: str) -> MetricSummary | None: ...
    def history(
        self,
        metric_key: str,
        *,
        x_axis: Literal["step", "relative_time", "timestamp"] = "step",
        start: int | datetime.timedelta | datetime.datetime | None = None,
        end: int | datetime.timedelta | datetime.datetime | None = None,
        max_points: int | None = None,
    ) -> MetricSeries: ...

class Api:
    def __init__(
        self,
        dir: str | os.PathLike[str] = ".",
        settings: Settings | None = None,
    ) -> None: ...
    def projects(self) -> list[Project]: ...
    def project(self, project_id: str) -> Project | None: ...
    def runs(self, project_id: str) -> list[RunRecord]: ...
    def run(self, path: str) -> RunRecord | None: ...
    def compare_runs(
        self,
        candidate_run_id: str,
        reference_run_id: str,
        *,
        metric_key: str,
        direction: Literal["minimize", "maximize"],
    ) -> ComparisonResult: ...
    def rank_runs(
        self,
        run_ids: list[str],
        *,
        metric_key: str,
        direction: Literal["minimize", "maximize"],
    ) -> RankingResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...

class Diagnostics:
    @property
    def pending_reports(self) -> int: ...
    @property
    def queue_full_errors(self) -> int: ...
    @property
    def persisted_reports(self) -> int: ...
    @property
    def writer_state(self) -> str: ...
    @property
    def last_write_error(self) -> str | None: ...
    @property
    def last_flush_run_id(self) -> str | None: ...
    @property
    def last_flush_status(self) -> str: ...
    @property
    def last_flush_error(self) -> str | None: ...

class ObjectiveMetric:
    @property
    def metric_key(self) -> str: ...
    @property
    def direction(self) -> Literal["minimize", "maximize"]: ...

class ObjectiveEvidence:
    @property
    def run_id(self) -> str: ...
    @property
    def run_status(self) -> Literal["running", "finished", "failed"]: ...
    @property
    def last_step(self) -> int | None: ...
    @property
    def last_value_f64(self) -> float | None: ...
    @property
    def completeness(
        self,
    ) -> Literal["complete", "partial", "unavailable", "invalid"]: ...
    @property
    def reasons(self) -> list[str]: ...

class ComparisonResult:
    @property
    def objective(self) -> ObjectiveMetric: ...
    @property
    def candidate(self) -> ObjectiveEvidence: ...
    @property
    def reference(self) -> ObjectiveEvidence: ...
    @property
    def completeness(
        self,
    ) -> Literal["complete", "partial", "unavailable", "invalid"]: ...
    @property
    def raw_delta(self) -> float | None: ...
    @property
    def relative_delta(self) -> float | None: ...
    @property
    def normalized_improvement(self) -> float | None: ...
    @property
    def outcome(self) -> Literal["improved", "regressed", "equal"] | None: ...
    @property
    def preference(
        self,
    ) -> Literal["candidate", "reference", "no_preference", "inconclusive"]: ...

class RankingEntry:
    @property
    def evidence(self) -> ObjectiveEvidence: ...
    @property
    def rank(self) -> int | None: ...

class RankingResult:
    @property
    def objective(self) -> ObjectiveMetric: ...
    @property
    def entries(self) -> list[RankingEntry]: ...

class MetricPoint:
    @property
    def run_id(self) -> str: ...
    @property
    def metric_key(self) -> str: ...
    @property
    def step(self) -> int: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def value_f64(self) -> float: ...
    @property
    def ingested_at(self) -> str: ...

class MetricSummary:
    @property
    def run_id(self) -> str: ...
    @property
    def metric_key(self) -> str: ...
    @property
    def effective_count(self) -> int: ...
    @property
    def last_step(self) -> int: ...
    @property
    def last_value_f64(self) -> float: ...
    @property
    def min_value_f64(self) -> float: ...
    @property
    def max_value_f64(self) -> float: ...

class Project:
    @property
    def project_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def created_at(self) -> str: ...

def init(
    *,
    project: str | None = None,
    dir: str | os.PathLike[str] | None = None,
    id: str | None = None,
    name: str | None = None,
    resume: bool | Literal["allow", "never", "must"] | None = None,
    settings: Settings | None = None,
) -> Run: ...
